### ISSUE TITLE
Paramedic should not fail if there is single target failure 

### ISSUE THREAD

**Issue by sgrebnov** [sgrebnov/cordova-paramedic#14]
```
Results at '/private/var/folders/g7/1y0b46qn11j73xp97xddxnd40000gn/T/tmp-868i0NCtttauBlj/platforms/ios/build/device/HelloCordova.ipa'
[....] Waiting up to 1 seconds for iOS device to be connected
No target specified for emulator. Deploying to iPhone-6s-Plus, 9.2 simulator
/private/var/folders/g7/1y0b46qn11j73xp97xddxnd40000gn/T/tmp-868i0NCtttauBlj/platforms/ios/build/emulator/HelloCordova.app/Info.plist file not found.

    at /Users/sg/Desktop/git/cordova-paramedic/lib/TestsRunner.js:120:27
    at /Users/sg/Desktop/git/cordova-paramedic/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:471:12)
sg@sgs-MacBook-Pro.local:/Users/sg/Desktop/git/cordova-paramedic/sample-config
```

**Comment by tommsawyer** [comment]
fixed in 535396868e31c5d245adab8c2a8e15e6e51d75b7
